version: "2.0.0"
services:
  # mongo:
  #   container_name: wiki-db
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - wiki-backend
  #   volumes:
  #     - mongo:/data/db

  # ollama:
  #   container_name: wiki-llama3.2
  #   image: ollama/ollama:latest
  #   volumes:
  #     - ollama:/root/.ollama
  #   tty: true
  #   restart: unless-stopped
  #   networks:
  #     - wiki-backend
  #   command: "ollama pull llama3.2"

  backend:
    container_name: wiki-backend
    build: ./backend
    volumes:
      - files:/backend/uploads
    ports:
      - 3000:3000
    networks:
      - wiki

  frontend:
    container_name: wiki-frontend
    build: ./Wiki
    ports:
      - "8080:80"
    networks:
      - wiki
  # s3:
  #   container_name: wiki-s3Bucket
  #   image: minio/minio:latest
  #   ports:
  #     - "9000:9000"
  #     - "9099:9099"
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: Password1
  #   volumes:
  #     - s3Bucket:/data
  #   command: server --address "0.0.0.0:9099" --console-address "0.0.0.0:9000" /data
  #   restart: always

volumes:
  # mongo: {}
  # ollama: {}
  files: {}
  # s3Bucket: {}
  # nexus-data: {}

networks:
  wiki:
    driver: bridge
# services:

