services:
  mongo:
    container_name: db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  ollama:
    container_name: llama3.2
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    tty: true
    restart: unless-stopped
    # command: "ollama pull llama3.2"

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - files:/backend/uploads

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

volumes:
  mongo: {}
  ollama: {}
  files: {}
  nexus-data: {}
