version: "2.0.0"
services:
  # mongo:
  #   container_name: wiki-db
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - wiki-backend
  #   volumes:
  #     - mongo:/data/db

  # ollama:
  #   container_name: wiki-llama3.2
  #   image: ollama/ollama:latest
  #   volumes:
  #     - ollama:/root/.ollama
  #   tty: true
  #   restart: unless-stopped
  #   networks:
  #     - wiki-backend
  #   command: "ollama pull llama3.2"

  backend:
    container_name: wiki-backend
    build: ./backend
    ports:
      - 3000:3000
    networks:
      - wiki

  frontend:
    container_name: wiki-frontend
    build: ./Wiki
    ports:
      - "8080:80"
    networks:
      - wiki

  Sonatype:
    container_name: wiki-nexus
    image: sonatype/nexus3:latest
    ports:
      - 8081:8081
    networks:
      - wiki
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

volumes:
  # mongo: {}
  # ollama: {}
  nexus-data: {}

networks:
  wiki:
    driver: bridge
