services:
  mongo:
    container_name: db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  ollama:
    container_name: llama3.2
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    tty: true
    restart: unless-stopped
    command: ollama run llama3.2

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 5050:5050

volumes:
  mongo: {}
  ollama: {}
