version: "1.0.1"
services:
  mongo:
    container_name: wiki-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - wiki-backend
    volumes:
      - mongo:/data/db

  ollama:
    container_name: wiki-llama3.2
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    tty: true
    restart: unless-stopped
    networks:
      - wiki-backend
    command: "ollama pull llama3.2"

  backend:
    container_name: wiki-backend
    build: ./backend
    volumes:
      - files:/backend/uploads
    networks:
      - wiki-backend

  frontend:
    container_name: wiki-frontend
    build: ./Wiki
    ports:
      - 5174:5174
    networks:
      - wiki-backend
      - wiki-frontend

  # nexus:
  #   container_name: wiki-nexus
  #   image: sonatype/nexus3
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - nexus-data:/nexus-data
  #   restart: unless-stopped

volumes:
  mongo: {}
  ollama: {}
  files: {}
  # nexus-data: {}

networks:
  wiki-backend:
    driver: bridge
  wiki-frontend:
    driver: bridge
